export const theme = {
  colors: {
    // Material 3 / Core Palette Tokens (Sapphire & Slate Design System)
    surface: "#f8fafc",
    surfaceDim: "#e2e8f0",
    surfaceBright: "#ffffff",
    surfaceContainerLowest: "#ffffff",
    surfaceContainerLow: "#f8fafc",
    surfaceContainer: "#f1f5f9",
    surfaceContainerHigh: "#e2e8f0",
    surfaceContainerHighest: "#cbd5e1",
    onSurface: "#0f172a",
    onSurfaceVariant: "#475569",
    inverseSurface: "#0f172a",
    inverseOnSurface: "#f8fafc",
    outline: "#94a3b8",
    outlineVariant: "#e2e8f0",
    surfaceTint: "#1e40af",
    primary: "#1e40af",
    onPrimary: "#ffffff",
    primaryContainer: "#dbeafe",
    onPrimaryContainer: "#1e3a8a",
    inversePrimary: "#93c5fd",
    secondary: "#475569",
    onSecondary: "#ffffff",
    secondaryContainer: "#f1f5f9",
    onSecondaryContainer: "#334155",
    tertiary: "#0f766e",
    onTertiary: "#ffffff",
    tertiaryContainer: "#ccfbf1",
    onTertiaryContainer: "#115e59",
    error: "#dc2626",
    onError: "#ffffff",
    errorContainer: "#fee2e2",
    onErrorContainer: "#991b1b",
    primaryFixed: "#dbeafe",
    primaryFixedDim: "#bfdbfe",
    onPrimaryFixed: "#172554",
    onPrimaryFixedVariant: "#1e40af",
    secondaryFixed: "#e2e8f0",
    secondaryFixedDim: "#cbd5e1",
    onSecondaryFixed: "#0f172a",
    onSecondaryFixedVariant: "#334155",
    tertiaryFixed: "#ccfbf1",
    tertiaryFixedDim: "#99f6e4",
    onTertiaryFixed: "#042f2e",
    onTertiaryFixedVariant: "#134e4a",
    background: "#f8fafc",
    onBackground: "#0f172a",
    surfaceVariant: "#f1f5f9",

    // Standard Semantic Aliases
    cardBg: "#ffffff",
    cardBorder: "#dce6eb",
    cardBorderSubtle: "#e5edf2",
    cardHeaderBg: "#f7fafb",
    textPrimary: "#0f172a",
    textSecondary: "#475569",
    textMuted: "#64748b",
    inputBg: "#ffffff",
    inputBorder: "#cbd5e1",
    inputFocusRing: "#2563eb",
    buttonBg: "#1e40af",
    buttonHoverBg: "#1d4ed8",
    buttonText: "#ffffff",
    accent: "#2563eb",
    accentLight: "#eff6ff",
    brandBg: "#dbeafe",
    brandText: "#1e40af",
    successBg: "#ecfdf5",
    successBorder: "#a7f3d0",
    successText: "#065f46",
    warningBg: "#fffbeb",
    warningBorder: "#fde68a",
    warningText: "#92400e",
    errorBg: "#fef2f2",
    errorBorder: "#fecaca",
    errorText: "#dc2626",
    infoBg: "#eff6ff",
    infoBorder: "#bfdbfe",
    infoText: "#1e40af",
    statCardBg: "#f4f8fa",
    statCardBorder: "#d6e6ec",
    statCardIconBg: "#e2f0f5",
    statCardIconText: "#19444f",
  },
  fontSizes: {
    xs: "0.75rem",     // 12px
    sm: "0.875rem",    // 14px
    base: "1rem",      // 16px
    lg: "1.125rem",    // 18px
    xl: "1.25rem",     // 20px
    "2xl": "1.5rem",   // 24px
    "3xl": "1.875rem", // 30px
    "4xl": "2.25rem",  // 36px
  },
  fontWeights: {
    normal: "400",
    medium: "500",
    semibold: "600",
    bold: "700",
    extrabold: "800",
  },
  buttonSizes: {
    xs: {
      padding: "0.375rem 0.625rem",
      fontSize: "0.75rem",
      height: "1.875rem",
      borderRadius: "0.375rem",
    },
    sm: {
      padding: "0.5rem 0.875rem",
      fontSize: "0.8125rem",
      height: "2.25rem",
      borderRadius: "0.375rem",
    },
    md: {
      padding: "0.625rem 1.125rem",
      fontSize: "0.875rem",
      height: "2.5rem",
      borderRadius: "0.375rem",
    },
    lg: {
      padding: "0.75rem 1.375rem",
      fontSize: "1rem",
      height: "2.875rem",
      borderRadius: "0.5rem",
    },
  },
  inputSizes: {
    sm: {
      padding: "0.4375rem 0.75rem",
      fontSize: "0.8125rem",
      height: "2.125rem",
      borderRadius: "0.375rem",
    },
    md: {
      padding: "0.5625rem 0.875rem",
      fontSize: "0.875rem",
      height: "2.375rem",
      borderRadius: "0.375rem",
    },
    lg: {
      padding: "0.6875rem 1rem",
      fontSize: "1rem",
      height: "2.75rem",
      borderRadius: "0.5rem",
    },
  },
  cardStyles: {
    default: {
      backgroundColor: "#ffffff",
      borderColor: "#dce6eb",
      borderRadius: "0.75rem",
      boxShadow: "0 4px 12px -2px rgba(25, 68, 79, 0.05)",
      padding: "1rem",
    },
    filter: {
      backgroundColor: "#ffffff",
      borderColor: "#dce6eb",
      borderRadius: "0.5rem",
      boxShadow: "0 1px 2px 0 rgba(25, 68, 79, 0.04)",
      padding: "0.625rem",
    },
    tableCard: {
      backgroundColor: "#ffffff",
      borderColor: "#dce6eb",
      borderRadius: "0.5rem",
      boxShadow: "0 1px 2px 0 rgba(25, 68, 79, 0.04)",
    },
  },
  borderRadius: {
    none: "0px",
    sm: "0.25rem",
    md: "0.375rem",
    lg: "0.5rem",
    xl: "0.75rem",
    "2xl": "1rem",
    full: "9999px",
    card: "0.75rem",
    input: "0.375rem",
    button: "0.375rem",
  },
  shadows: {
    none: "none",
    "2xs": "0 1px 2px 0 rgba(0, 0, 0, 0.03)",
    xs: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
    sm: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
    md: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
    xl: "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
    card: "0 4px 12px -2px rgba(0, 0, 0, 0.05)",
    button: "0 2px 6px rgba(30, 64, 175, 0.2)",
  },
  widthPresets: {
    full: "100%",
    auto: "auto",
    xs: "20rem",
    sm: "24rem",
    md: "28rem",
    lg: "32rem",
    xl: "36rem",
    "2xl": "42rem",
    screen: "100vw",
  },
  heightPresets: {
    full: "100%",
    auto: "auto",
    inputSm: "2.125rem",
    inputMd: "2.375rem",
    inputLg: "2.75rem",
    buttonSm: "2.25rem",
    buttonMd: "2.5rem",
    header: "3.5rem",
    navbar: "3.5rem",
    screen: "100vh",
  },
  padding: {
    none: "0rem",
    xs: "0.25rem 0.5rem",
    sm: "0.375rem 0.75rem",
    md: "0.5rem 1rem",
    lg: "0.75rem 1.25rem",
    xl: "1rem 1.5rem",
    card: "1rem",
    cardDense: "0.75rem",
    navbar: "0.5rem 1.25rem",
    navLink: "0.5rem 0.875rem",
  },
  margins: {
    none: "0rem",
    xs: "0.25rem",
    sm: "0.5rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
  },
  spacing: {
    0: "0rem",
    0.5: "0.125rem",
    1: "0.25rem",
    1.5: "0.375rem",
    2: "0.5rem",
    2.5: "0.625rem",
    3: "0.75rem",
    4: "1rem",
    5: "1.25rem",
    6: "1.5rem",
    8: "2rem",
    10: "2.5rem",
    12: "3rem",
  },
  iconSizes: {
    xs: 14,
    sm: 16,
    md: 20,
    nav: 18,
    logo: 24,
    lg: 24,
    xl: 32,
  },
  navbar: {
    height: "3.5rem",
    padding: "0.5rem 1.25rem",
    logoBadgePadding: "0.375rem",
    logoSize: "1.5rem",
    titleFontSize: "1.125rem",
    navLinkPadding: "0.5rem 0.875rem",
    navLinkFontSize: "0.875rem",
    navLinkIconSize: "1.125rem",
    gap: "0.5rem",
  },
  tableSizing: {
    cellPadding: "0.625rem 0.75rem",
    headerPadding: "0.75rem 0.75rem",
    rowHeight: "2.75rem",
    fontSize: "0.8125rem",
    headerFontSize: "0.75rem",
  },
  typography: {
    fontFamily: "var(--font-geist-sans), system-ui, sans-serif",
    titleSize: "1.25rem",
    titleWeight: "700",
    labelSize: "0.75rem",
    labelWeight: "600",
  },
  badgeVariants: {
    primary: "bg-[#dbeafe] text-[#1e40af] border border-[#bfdbfe]",
    secondary: "bg-[#f1f5f9] text-[#475569] border border-[#cbd5e1]",
    success: "bg-[#ecfdf5] text-[#065f46] border border-[#a7f3d0]",
    warning: "bg-[#fffbeb] text-[#92400e] border border-[#fde68a]",
    danger: "bg-[#fee2e2] text-[#dc2626] border border-[#fecaca]",
    brand: "bg-[#dbeafe] text-[#1e40af] border border-[#93c5fd]",
    info: "bg-[#eff6ff] text-[#1e40af] border border-[#bfdbfe]",
  },
  buttonVariants: {
    primary: "bg-[#1e40af] text-white hover:bg-[#1d4ed8] active:bg-[#1e3a8a]",
    secondary: "bg-[#eff6ff] text-[#1e40af] hover:bg-[#dbeafe] border border-[#bfdbfe] active:bg-[#93c5fd]/50",
    danger: "bg-[#fee2e2] text-[#dc2626] hover:bg-[#fecaca] border border-[#fecaca] active:bg-[#fca5a5]",
    outline: "bg-transparent text-[#1e40af] border border-[#93c5fd] hover:bg-[#eff6ff] hover:border-[#1e40af] active:bg-[#dbeafe]",
    ghost: "bg-transparent text-[#1e40af] hover:bg-[#eff6ff] hover:text-[#1e3a8a] active:bg-[#dbeafe]",
  },
  cardVariants: {
    default: "bg-white border border-[#dce6eb] shadow-xs rounded-xl p-4 transition-all hover:border-[#19444f]/25",
    filter: "bg-white border border-[#dce6eb] shadow-2xs rounded-lg p-2.5 text-[#102a32]",
    table: "bg-white border border-[#dce6eb] shadow-xs rounded-lg flex flex-col overflow-hidden",
  },
  styles: {
    // Page & Layout
    pageContainer: "bg-[#f8fafc] font-sans",
    
    // Cards
    card: "bg-white border border-[#dce6eb] shadow-xs transition-all hover:border-[#19444f]/25",
    cardHeader: "flex items-center justify-between pb-3 mb-3 border-b border-[#e5edf2]",
    cardTitle: "font-bold text-[#102a32] text-sm tracking-tight",
    cardFooter: "pt-3 mt-3 border-t border-[#e5edf2] flex items-center justify-end gap-2",
    filterCard: "bg-white rounded-lg border border-[#dce6eb] shadow-xs text-[#102a32]",
    filterBar: "bg-white p-2.5 rounded-lg border border-[#dce6eb] shadow-2xs mb-2 shrink-0",
    tableCard: "bg-white rounded-lg border border-[#dce6eb] shadow-xs flex flex-col overflow-hidden",

    // Typography
    title: "font-bold text-[#0f172a] tracking-tight",
    subtitle: "text-[#475569]",
    label: "block font-semibold text-[#475569] mb-1",

    // Form Controls
    input: "bg-white text-[#0f172a] border border-[#cbd5e1] rounded-md focus:outline-none focus:ring-2 focus:ring-[#2563eb]/20 focus:border-[#2563eb] font-medium placeholder-slate-400 transition-all",
    inputError: "border-rose-500 text-rose-900 focus:ring-rose-500/20 focus:border-rose-600",
    inputErrorText: "mt-1 text-[11px] text-rose-600 font-medium",
    select: "bg-white text-[#0f172a] border border-[#cbd5e1] rounded-md focus:outline-none focus:ring-2 focus:ring-[#2563eb]/20 focus:border-[#2563eb] font-medium transition-all cursor-pointer",
    selectOption: "bg-white text-[#0f172a] font-normal",
    selectError: "border-rose-500 text-rose-900 focus:ring-rose-500/20 focus:border-rose-600",

    // Buttons
    button: "font-semibold text-white bg-[#1e40af] hover:bg-[#1d4ed8] active:bg-[#1e3a8a] rounded-md transition-colors shadow-xs flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50",
    buttonSecondary: "font-semibold text-[#1e40af] bg-[#eff6ff] hover:bg-[#dbeafe] border border-[#bfdbfe] active:bg-[#93c5fd]/50 rounded-md transition-colors shadow-xs flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50",
    buttonDanger: "font-semibold text-[#dc2626] bg-[#fee2e2] hover:bg-[#fecaca] border border-[#fecaca] active:bg-[#fca5a5] transition-colors shadow-xs flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50",
    buttonOutline: "bg-transparent text-[#1e40af] border border-[#93c5fd] hover:bg-[#eff6ff] hover:border-[#1e40af] active:bg-[#dbeafe] rounded-md transition-colors flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50",
    buttonGhost: "bg-transparent text-[#1e40af] hover:bg-[#eff6ff] hover:text-[#1e3a8a] active:bg-[#dbeafe] rounded-md transition-colors flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50",
    errorAlert: "rounded-md bg-[#fee2e2] border border-[#fecaca] text-[#991b1b] font-medium flex items-center gap-2",

    // Badges
    badgePrimary: "bg-[#dbeafe] text-[#1e40af] border border-[#bfdbfe]",
    badgeSecondary: "bg-[#f1f5f9] text-[#475569] border border-[#cbd5e1]",
    badgeSuccess: "bg-[#ecfdf5] text-[#065f46] border border-[#a7f3d0]",
    badgeWarning: "bg-[#fffbeb] text-[#92400e] border border-[#fde68a]",
    badgeDanger: "bg-[#fee2e2] text-[#dc2626] border border-[#fecaca]",
    badgeBrand: "bg-[#dbeafe] text-[#1e40af] border border-[#93c5fd]",
    badgeInfo: "bg-[#eff6ff] text-[#1e40af] border border-[#bfdbfe]",

    // Navbar Tokens
    navbar: "w-full h-14 shrink-0 px-5 flex items-center justify-between z-40 bg-white border-b border-[#e2e8f0] shadow-xs",
    brandBadge: "p-1.5 rounded-lg bg-[#dbeafe] flex items-center justify-center font-bold text-[#1e40af] tracking-tight",
    brandTitle: "text-base font-extrabold tracking-tight text-[#1e40af]",
    navLinkActive: "px-3 py-1.5 text-sm font-semibold rounded-lg transition-colors flex items-center gap-2 bg-[#f1f5f9] text-[#1e40af]",
    navLinkInactive: "px-3 py-1.5 text-sm font-semibold rounded-lg transition-colors flex items-center gap-2 text-[#475569] hover:bg-[#f1f5f9] hover:text-[#0f172a]",
    navDropdownMenu: "absolute bg-white rounded-lg shadow-xl border border-[#e2e8f0] z-50 animate-in fade-in duration-100",
    navDropdownItemActive: "flex items-center gap-2 font-semibold bg-[#f1f5f9] text-[#1e40af] transition-colors",
    navDropdownItemInactive: "flex items-center gap-2 font-medium text-[#475569] hover:bg-[#f8fafc] hover:text-[#0f172a] transition-colors",
    logoutButton: "font-semibold text-[#dc2626] bg-[#fee2e2] hover:bg-[#fee2e2]/80 rounded-md border border-[#fecaca] transition-colors flex items-center gap-1.5 cursor-pointer disabled:opacity-50",

    // Dashboard Tokens
    dashboardBanner: "bg-gradient-to-r from-[#1e40af] via-[#2563eb] to-[#0f766e] rounded-xl text-white shadow-md relative overflow-hidden",
    dashboardKpiCard: "bg-gradient-to-br from-white via-[#f7fafb] to-[#edf5f8] rounded-xl border border-[#d6e6ec] shadow-xs flex flex-col justify-between transition-all hover:shadow-md hover:border-[#19444f]/35",
    dashboardKpiTitle: "font-semibold text-[#3d565e] uppercase tracking-wider",
    dashboardKpiValue: "font-extrabold text-[#102a32]",
    dashboardQuickActionCard: "bg-white border border-[#e2e8f0] rounded-lg shadow-2xs hover:border-[#2563eb] hover:shadow-xs transition-all flex flex-col items-center text-center group cursor-pointer",

    // Login Page Tokens
    loginPageContainer: "flex items-center justify-center bg-[#f8fafc] font-sans",
    loginCard: "bg-white rounded-xl border border-[#e2e8f0] shadow-xl space-y-4",
    loginHeaderIcon: "rounded-xl bg-[#f1f5f9] text-[#1e40af] border border-[#cbd5e1] flex items-center justify-center shadow-xs",
    loginSubmitButton: "font-bold text-white bg-[#1e40af] hover:bg-[#1d4ed8] active:bg-[#1e3a8a] rounded-lg transition-all shadow-md flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50",

    // Modals
    modalOverlay: "fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-xs animate-in fade-in duration-150",
    modalCard: "bg-white rounded-xl border border-[#e2e8f0] shadow-2xl w-full overflow-hidden flex flex-col max-h-[90vh]",
    modalHeader: "flex items-center justify-between px-4 py-3 border-b border-[#e2e8f0] bg-[#f8fafc] shrink-0",
    modalIcon: "text-[#1e40af]",
    modalTitle: "text-sm font-bold text-[#0f172a] tracking-tight",
    modalSubtitle: "text-xs text-[#475569]",
    modalCloseButton: "p-1 rounded-md text-[#475569] hover:bg-[#f1f5f9] hover:text-[#0f172a] transition-colors cursor-pointer",
    modalBody: "p-4 overflow-y-auto flex-1",
    modalFooter: "flex items-center justify-end gap-2 px-4 py-3 border-t border-[#e2e8f0] bg-[#f8fafc] shrink-0",

    // PageHeader
    pageHeader: "flex items-center justify-between gap-3 mb-2 shrink-0",
    pageHeaderIcon: "text-[#1e40af]",
    pageHeaderTitle: "text-base font-bold text-[#0f172a] tracking-tight flex items-center gap-2",
    pageHeaderSubtitle: "text-xs text-[#475569]",

    // StatCard
    statCard: "bg-gradient-to-br from-white via-[#f7fafb] to-[#edf5f8] rounded-xl border border-[#d6e6ec] shadow-xs p-4 flex flex-col justify-between transition-all hover:shadow-md hover:border-[#19444f]/35 hover:-translate-y-0.5",
    statCardTitle: "font-semibold text-xs text-[#3d565e] uppercase tracking-wider",
    statCardIcon: "p-2 rounded-lg bg-[#e2f0f5] text-[#19444f] border border-[#cae2eb] shadow-2xs",
    statCardValue: "text-2xl font-extrabold text-[#102a32] tracking-tight",
    statCardSubtitle: "mt-1 flex items-center justify-between text-xs text-[#4d6a74]",
    statCardPositiveTrend: "text-emerald-700 font-semibold",
    statCardNegativeTrend: "text-rose-600 font-semibold",
    statCardNeutralTrend: "text-[#4d6a74]",
    statCardAction: "mt-3 pt-2 border-t border-[#dbe8ee] flex justify-end",

    // Tables
    tableContainer: "bg-white rounded-lg border border-[#e2e8f0] shadow-2xs flex-1 flex flex-col overflow-hidden min-h-0",
    table: "w-full text-left text-xs border-collapse",
    tableHeaderRow: "bg-[#f8fafc] border-b border-[#e2e8f0] font-semibold uppercase tracking-wider text-[#475569] sticky top-0 z-10",
    tableBody: "divide-y divide-[#e2e8f0]/80",
    tableRow: "hover:bg-[#f1f5f9]/80 transition-colors text-[#0f172a]",
    tableHead: "py-2.5 px-3 font-semibold",
    tableCell: "py-2.5 px-3 align-middle",

    // Watermarks
    watermarkReceipt: "w-full text-center py-1 mt-2 border-t border-dashed border-[#e2e8f0] print:border-[#000000] text-[10px] font-bold text-[#0f172a] print:text-black opacity-100 print:opacity-100 shrink-0 select-none",
    watermarkReceiptLink: "font-bold hover:text-[#1e40af] print:text-black print:no-underline",
    watermarkPage: "w-full text-center py-1 mt-auto shrink-0 text-[10px] sm:text-xs font-medium text-[#64748b] opacity-60 print:opacity-100 print:text-black hover:opacity-100 transition-opacity select-none",
    watermarkPageLink: "font-semibold hover:text-[#1e40af] print:text-black print:no-underline",
  },
} as const;

export type Theme = typeof theme;
export default theme;
